#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

TARGET = Path("src/ui-language-0.3.27.js")
SENTINEL = "/* PU2PNY-I18N-0.3.31.115-COVERAGE */"

CATALOG = {
    "Não lidas 0": ["Unread 0", "No leídas 0"],
    "APRS-IS automático · ativo por padrão após a configuração inicial": ["Automatic APRS-IS · enabled by default after initial setup", "APRS-IS automático · activado de forma predeterminada después de la configuración inicial"],
    "Medida somente durante uma conexão.": ["Measured only during a connection.", "Medido solo durante una conexión."],
    "Esta caixa não inicia chamada. Use o indicativo/ID digital no próprio rádio e o PTT para chamar ou aceitar uma chamada pendente.": ["This box does not start a call. Use the callsign/digital ID on the radio itself and PTT to call or accept a pending call.", "Este cuadro no inicia una llamada. Use el indicativo/ID digital en la propia radio y el PTT para llamar o aceptar una llamada pendiente."],
    "1. Autorize o outro PU2PNY uma vez. 2. No D-Star, use o indicativo no URCALL; no DMR, faça uma Private Call para o ID digital do destino (Talkgroup não inicia Direct). 3. Aperte o PTT: o hotspot tenta o caminho UDP direto. 4. Se NAT/CGNAT impedir o caminho direto, usa automaticamente o relay autenticado. 5. O hotspot chamado só troca sua conexão quando o operador aceitar pelo rádio. 6. Ao encerrar, o gateway anterior é restaurado automaticamente.": ["1. Authorize the other PU2PNY once. 2. In D-Star, use the callsign in URCALL; in DMR, make a Private Call to the destination digital ID (Talkgroup does not start Direct). 3. Press PTT: the hotspot tries the direct UDP path. 4. If NAT/CGNAT prevents the direct path, it automatically uses the authenticated relay. 5. The called hotspot changes its connection only after the operator accepts on the radio. 6. When the call ends, the previous gateway is restored automatically.", "1. Autorice el otro PU2PNY una vez. 2. En D-Star, use el indicativo en URCALL; en DMR, haga una Private Call al ID digital de destino (Talkgroup no inicia Direct). 3. Presione PTT: el hotspot intenta la ruta UDP directa. 4. Si NAT/CGNAT impide la ruta directa, usa automáticamente el relay autenticado. 5. El hotspot llamado solo cambia su conexión cuando el operador acepta desde la radio. 6. Al finalizar, el gateway anterior se restaura automáticamente."],
    "Negociação, criptografia, fallback Direct→Relay e espera de aceitação são testáveis em software/CI. RF e CGNAT reais entre dois hotspots continuam exigindo teste físico A↔B.": ["Negotiation, encryption, Direct→Relay fallback and acceptance waiting are testable in software/CI. Real RF and CGNAT between two hotspots still require a physical A↔B test.", "La negociación, el cifrado, el fallback Direct→Relay y la espera de aceptación se pueden probar en software/CI. RF y CGNAT reales entre dos hotspots siguen requiriendo una prueba física A↔B."],
    "Detecção automática ao entrar na Internet, renderer e integração física sem disputar a serial do MMDVM.": ["Automatic detection when Internet becomes available, renderer and physical integration without competing for the MMDVM serial port.", "Detección automática al disponer de Internet, renderer e integración física sin competir por el puerto serie de la MMDVM."],
    "Rastreando sinais Wi-Fi / Ethernet · IP real TX/RX usa indicativo, destino, duração, BER/RSSI quando disponíveis.": ["Tracking Wi-Fi / Ethernet signals · real IP. TX/RX uses callsign, destination, duration and BER/RSSI when available.", "Rastreando señales Wi-Fi / Ethernet · IP real. TX/RX usa indicativo, destino, duración y BER/RSSI cuando están disponibles."],
    "Ao conectar à Internet, o PU2PNY executa uma detecção limitada do hardware. O catálogo identifica modelo/resolução quando o equipamento responde com evidência real. Um TFT só poderá ser oferecido quando existir asset oficial publicado com URL + SHA-256. Mesmo assim, a gravação exigirá confirmação explícita no painel.": ["When Internet becomes available, PU2PNY performs limited hardware detection. The catalog identifies model/resolution only when the equipment responds with real evidence. A TFT can only be offered when an official asset is published with URL + SHA-256. Even then, flashing requires explicit confirmation in the panel.", "Al conectarse a Internet, PU2PNY realiza una detección limitada del hardware. El catálogo identifica modelo/resolución solo cuando el equipo responde con evidencia real. Un TFT solo podrá ofrecerse cuando exista un recurso oficial publicado con URL + SHA-256. Aun así, la grabación requiere confirmación explícita en el panel."],
    "LCD 0x27/0x3F: HD44780/PCF8574 tratado como candidato até confirmação.": ["LCD 0x27/0x3F: HD44780/PCF8574 treated as a candidate until confirmed.", "LCD 0x27/0x3F: HD44780/PCF8574 tratado como candidato hasta su confirmación."],
    "USB, SPI, HDMI/DRM e touch podem ser detectados como hardware real. Nesta Alpha, display genérico é identificado e informado; renderer touch gráfico completo continua fase posterior e não bloqueia o sistema.": ["USB, SPI, HDMI/DRM and touch can be detected as real hardware. In this Alpha, a generic display is identified and reported; the full graphical touch renderer remains a later phase and does not block the system.", "USB, SPI, HDMI/DRM y touch pueden detectarse como hardware real. En esta Alpha, una pantalla genérica se identifica y se informa; el renderer táctil gráfico completo sigue siendo una fase posterior y no bloquea el sistema."],
    "Cockpit técnico em tempo real. Dados brutos ficam recolhidos; ajustes RF usam confirmação e rollback.": ["Real-time technical cockpit. Raw data stays collapsed; RF adjustments use confirmation and rollback.", "Cockpit técnico en tiempo real. Los datos brutos permanecen contraídos; los ajustes RF usan confirmación y rollback."],
    "Este controle altera o nível de saída RF do modem. Não representa watts medidos e é separado de TXLevel/desvio.": ["This control changes the modem RF output level. It does not represent measured watts and is separate from TXLevel/deviation.", "Este control cambia el nivel de salida RF del módem. No representa vatios medidos y es independiente de TXLevel/desviación."],
    "Configure RF, perfis e redes digitais em uma única tela. Abrir esta página não reinicia o rádio; alterações só são aplicadas quando você salvar ou ativar.": ["Configure RF, profiles and digital networks on one screen. Opening this page does not restart the radio; changes are applied only when you save or activate.", "Configure RF, perfiles y redes digitales en una sola pantalla. Abrir esta página no reinicia la radio; los cambios solo se aplican al guardar o activar."],
    "Somente o indicativo configurado. Envie PNYARM e, dentro de 30 segundos, uma ação: PNYRBT reinicia; PNYOFF faz shutdown seguro; PNYDMR , PNYDST , PNYYSF , PNYP25 , PNYNXD ou PNYPOC ativam um perfil já salvo. O armamento vale para uma única ação. Corte físico da alimentação exige hardware externo.": ["Configured callsign only. Send PNYARM and, within 30 seconds, one action: PNYRBT restarts; PNYOFF performs a safe shutdown; PNYDMR, PNYDST, PNYYSF, PNYP25, PNYNXD or PNYPOC activates an already-saved profile. Arming is valid for one action only. Physically cutting power requires external hardware.", "Solo el indicativo configurado. Envíe PNYARM y, dentro de 30 segundos, una acción: PNYRBT reinicia; PNYOFF realiza un apagado seguro; PNYDMR, PNYDST, PNYYSF, PNYP25, PNYNXD o PNYPOC activa un perfil ya guardado. El armado vale para una sola acción. El corte físico de alimentación requiere hardware externo."],
    "B (padrão PU2PNY)": ["B (PU2PNY default)", "B (predeterminado de PU2PNY)"],
    "A API Key é usada para recursos de gerenciamento BrandMeister e não substitui a Hotspot Security. O PU2PNY não pede API Secret.": ["The API Key is used for BrandMeister management features and does not replace Hotspot Security. PU2PNY does not request an API Secret.", "La API Key se usa para funciones de administración de BrandMeister y no sustituye Hotspot Security. PU2PNY no solicita API Secret."],
    "Cada protocolo pode guardar sua própria frequência e rede. Ao ativar, o PU2PNY aplica somente as diferenças, com rollback.": ["Each protocol can store its own frequency and network. When activated, PU2PNY applies only the differences, with rollback.", "Cada protocolo puede guardar su propia frecuencia y red. Al activarlo, PU2PNY aplica solo las diferencias, con rollback."],
    "Para MMDVM_HS, BER alto costuma ser corrigido pelo RXOffset. Teste em Standby, transmita pelo rádio e compare o BER real. O painel recomenda somente o melhor valor realmente medido nesta sessão.": ["For MMDVM_HS, high BER is usually corrected with RXOffset. Test in Standby, transmit from the radio and compare the real BER. The panel recommends only the best value actually measured in this session.", "Para MMDVM_HS, un BER alto suele corregirse con RXOffset. Pruebe en Standby, transmita desde la radio y compare el BER real. El panel recomienda solo el mejor valor realmente medido en esta sesión."],
    "Cada teste altera somente RXOffset, com backup e rollback se o MMDVMHost não voltar. Frequências, TXOffset, protocolo, DMR simplex/duplex e gateway não são reconfigurados por este controle.": ["Each test changes only RXOffset, with backup and rollback if MMDVMHost does not return. Frequencies, TXOffset, protocol, DMR simplex/duplex and gateway are not reconfigured by this control.", "Cada prueba cambia solo RXOffset, con copia de seguridad y rollback si MMDVMHost no vuelve. Las frecuencias, TXOffset, protocolo, DMR simplex/dúplex y gateway no se reconfiguran mediante este control."],
    "Wi‑Fi, conexão via cabo, mDNS, qualidade e rota até o servidor digital.": ["Wi-Fi, wired connection, mDNS, quality and route to the digital server.", "Wi-Fi, conexión por cable, mDNS, calidad y ruta hasta el servidor digital."],
    "Somente resolvedores efetivamente ativos na interface da rota padrão.": ["Only resolvers that are effectively active on the default-route interface.", "Solo resolutores que estén realmente activos en la interfaz de la ruta predeterminada."],
    "A comparação é informativa. Troca de DNS faz backup do perfil e volta ao anterior se a resolução falhar.": ["The comparison is informational. Changing DNS backs up the profile and restores the previous one if resolution fails.", "La comparación es informativa. Cambiar el DNS hace una copia de seguridad del perfil y restaura el anterior si falla la resolución."],
    "Busque redes para analisar a ocupação dos canais.": ["Scan networks to analyze channel occupancy.", "Busque redes para analizar la ocupación de los canales."],
    "A segunda rede funciona como backup. Se a atual cair, o PU2PNY tenta a outra; quando ambas estão visíveis, a seleção automática considera o sinal sem trocar por diferenças pequenas. Ethernet tem prioridade de rota quando disponível.": ["The second network acts as a backup. If the current one fails, PU2PNY tries the other; when both are visible, automatic selection considers signal strength without switching for small differences. Ethernet has route priority when available.", "La segunda red funciona como respaldo. Si la actual falla, PU2PNY intenta la otra; cuando ambas están visibles, la selección automática considera la señal sin cambiar por diferencias pequeñas. Ethernet tiene prioridad de ruta cuando está disponible."],
    "“Online” significa que o hotspot tem rota e conectividade observada. “Sem resposta ICMP” em um hop não significa, sozinho, falha: alguns roteadores filtram esse tipo de resposta.": ["“Online” means the hotspot has a route and observed connectivity. “No ICMP response” at one hop does not by itself mean failure: some routers filter this type of response.", "“Online” significa que el hotspot tiene ruta y conectividad observada. “Sin respuesta ICMP” en un salto no significa por sí solo un fallo: algunos routers filtran este tipo de respuesta."],
    "Escolha o protocolo, a rede e o servidor. Apenas uma alteração real reconecta o rádio.": ["Choose the protocol, network and server. Only an actual change reconnects the radio.", "Elija el protocolo, la red y el servidor. Solo un cambio real vuelve a conectar la radio."],
    "A página oficial RadioID pode exigir proteção anti-bot e nem sempre aceita uma URL que abra diretamente um resultado específico. Por isso o PU2PNY mostra aqui o registro já associado à atividade observada e mantém um botão separado para a busca oficial.": ["The official RadioID page may require anti-bot protection and does not always accept a URL that opens a specific result directly. Therefore PU2PNY shows here the record already associated with the observed activity and keeps a separate button for the official search.", "La página oficial de RadioID puede requerir protección anti-bot y no siempre acepta una URL que abra directamente un resultado específico. Por eso PU2PNY muestra aquí el registro ya asociado con la actividad observada y mantiene un botón separado para la búsqueda oficial."],
    "Relógio, sincronização, operação do rádio e energia.": ["Clock, synchronization, radio operation and power.", "Reloj, sincronización, operación de radio y energía."],
    "Desligar o operacional para MMDVMHost e gateways, mas mantém painel, rede e acesso para manutenção.": ["Turn off operational MMDVMHost and gateways while keeping the panel, network and maintenance access available.", "Desactiva la operación de MMDVMHost y gateways, pero mantiene el panel, la red y el acceso de mantenimiento."],
    "O limite fica no MMDVMHost, não no navegador. Se uma transmissão contínua chegar a 180 segundos, o núcleo de rádio interrompe conforme o timeout nativo.": ["The limit is enforced by MMDVMHost, not the browser. If a continuous transmission reaches 180 seconds, the radio core stops it according to the native timeout.", "El límite se aplica en MMDVMHost, no en el navegador. Si una transmisión continua llega a 180 segundos, el núcleo de radio la interrumpe según el timeout nativo."],
    "Verificação leve de componentes oficiais, listas públicas, espaço e serviços. Não executa upgrade completo do Debian e não altera RF.": ["Lightweight verification of official components, public lists, storage and services. It does not perform a full Debian upgrade and does not change RF.", "Verificación ligera de componentes oficiales, listas públicas, espacio y servicios. No realiza una actualización completa de Debian ni modifica RF."],
    "Use os botões abaixo antes de cortar a alimentação. Reiniciar e desligar exigem confirmação.": ["Use the buttons below before cutting power. Restarting and shutting down require confirmation.", "Use los botones siguientes antes de cortar la alimentación. Reiniciar y apagar requieren confirmación."],
    "Não desligue o hotspot e não atualize a página. Assim que o PU2PNY voltar na nova rede, esta página abrirá Hardware automaticamente.": ["Do not power off the hotspot or refresh the page. As soon as PU2PNY returns on the new network, this page will open Hardware automatically.", "No apague el hotspot ni actualice la página. En cuanto PU2PNY vuelva a la nueva red, esta página abrirá Hardware automáticamente."],
    "Preparação automática quando houver internet Atualiza os índices e instala somente drivers/firmware oficiais que estiverem faltando. Não executa upgrade completo do Debian.": ["Automatic preparation when Internet is available. Updates indexes and installs only missing official drivers/firmware. It does not perform a full Debian upgrade.", "Preparación automática cuando haya Internet. Actualiza los índices e instala solo los controladores/firmware oficiales que falten. No realiza una actualización completa de Debian."],
    "É uma única API Key/token. Não existe campo de segredo adicional da API no PU2PNY. A chave de API não autentica o hotspot e não substitui a senha de segurança do hotspot.": ["It is a single API Key/token. PU2PNY has no additional API secret field. The API key does not authenticate the hotspot and does not replace the hotspot security password.", "Es una única API Key/token. PU2PNY no tiene un campo adicional de secreto de API. La clave de API no autentica el hotspot ni sustituye la contraseña de seguridad del hotspot."],
    "Ajuste avançado da rede DMR": ["Advanced DMR network settings", "Ajustes avanzados de la red DMR"],
    "Crossmode Planejado — ainda não habilitado nesta Alpha": ["Crossmode Planned — not enabled in this Alpha yet", "Crossmode Planificado — todavía no habilitado en esta Alpha"],
}


def main() -> None:
    text = TARGET.read_text(encoding="utf-8")
    if SENTINEL in text:
        print("I18N_PATCH_ALREADY_APPLIED")
        return
    marker = "let language="
    if text.count(marker) != 1:
        raise SystemExit("i18n insertion marker missing or ambiguous")
    payload = json.dumps(CATALOG, ensure_ascii=False, separators=(",", ":"))
    block = f"\n{SENTINEL}\nObject.assign(D,{payload});\n"
    TARGET.write_text(text.replace(marker, block + marker, 1), encoding="utf-8")
    print(f"I18N_PATCH_APPLIED entries={len(CATALOG)}")


if __name__ == "__main__":
    main()
