#!/usr/bin/env bash
set -euo pipefail
IMAGE="${1:?image required}"
VERSION="${2:-0.1.8-alpha}"
RAW="/tmp/2PNY-OS-${VERSION}-network-validate.img"
ROOT=/mnt/2pny-018
LOOP=''
PID=''
cleanup(){
  set +e
  [[ -n "$PID" ]] && sudo kill "$PID" 2>/dev/null || true
  sudo umount "$ROOT/proc" 2>/dev/null || true
  sudo umount "$ROOT/dev" 2>/dev/null || true
  sudo umount "$ROOT/sys" 2>/dev/null || true
  sudo umount "$ROOT/boot/firmware" 2>/dev/null || true
  sudo umount "$ROOT" 2>/dev/null || true
  [[ -n "$LOOP" ]] && sudo losetup -d "$LOOP" 2>/dev/null || true
  sudo rm -f "$RAW"
}
trap cleanup EXIT

xz -t "$IMAGE"
EXPECTED="$(awk '{print $1}' "${IMAGE}.sha256")"
ACTUAL="$(sha256sum "$IMAGE" | awk '{print $1}')"
[[ "$EXPECTED" == "$ACTUAL" ]]
sudo rm -f "$RAW"
sudo sh -c "xz -dc '$IMAGE' > '$RAW'"
LOOP="$(sudo losetup --find --partscan --show "$RAW")"
for _ in {1..40}; do [[ -b "${LOOP}p2" ]] && break; sleep .25; done
sudo mkdir -p "$ROOT"
sudo mount "${LOOP}p2" "$ROOT"
sudo mkdir -p "$ROOT/boot/firmware"
sudo mount "${LOOP}p1" "$ROOT/boot/firmware"

AP="$ROOT/etc/NetworkManager/system-connections/2pny-setup.nmconnection"
ETH="$ROOT/etc/NetworkManager/system-connections/2pny-ethernet-setup.nmconnection"

echo '[1/9] image and runtime contract'
grep -q '^0.1.8-alpha$' "$ROOT/etc/2pny/version"
test -x "$ROOT/usr/local/bin/2pnyd"
test -x "$ROOT/usr/bin/nmcli"
test -x "$ROOT/usr/sbin/NetworkManager"
test -x "$ROOT/usr/sbin/dnsmasq"
test -x "$ROOT/usr/sbin/nft"
test -e "$ROOT/etc/cloud/cloud-init.disabled"

echo '[2/9] NetworkManager boot authority'
test -L "$ROOT/etc/systemd/system/multi-user.target.wants/NetworkManager.service"
test -L "$ROOT/etc/systemd/system/multi-user.target.wants/2pnyd.service"
test -L "$ROOT/etc/systemd/system/multi-user.target.wants/2pny-firstboot.service"
test -L "$ROOT/etc/systemd/system/multi-user.target.wants/2pny-setup-watch.service"
test -f "$ROOT/etc/systemd/system/NetworkManager.service.d/10-2pny-regdom.conf"
grep -q 'Before=NetworkManager.service' "$ROOT/etc/systemd/system/2pny-regdom.service"
grep -q 'iw reg set BR' "$ROOT/usr/local/sbin/2pny-regdom"

echo '[3/9] open Wi-Fi AP profile generated by target nmcli'
test -s "$AP"
grep -q '^id=2PNY-SETUP$' "$AP"
grep -q '^autoconnect=true$' "$AP"
grep -q '^autoconnect-retries=0$' "$AP"
grep -q '^mode=ap$' "$AP"
grep -q '^ssid=2PNY-SETUP$' "$AP"
grep -q '^key-mgmt=none$' "$AP"
grep -q '^pmf=1$' "$AP"
grep -q '^method=shared$' "$AP"
grep -q '^address1=10.42.0.1/24' "$AP"
grep -q '^never-default=true$' "$AP"
! grep -q '^psk=' "$AP"

# Parse/round-trip the final profile with the exact nmcli shipped in the image.
sudo chroot "$ROOT" /bin/bash -c 'nmcli --offline connection modify type wifi < /etc/NetworkManager/system-connections/2pny-setup.nmconnection > /tmp/2pny-ap-roundtrip.nmconnection'
grep -q '^id=2PNY-SETUP$' "$ROOT/tmp/2pny-ap-roundtrip.nmconnection"
grep -q '^pmf=1$' "$ROOT/tmp/2pny-ap-roundtrip.nmconnection"

echo '[4/9] simultaneous direct Ethernet profile'
test -s "$ETH"
grep -q '^id=2PNY-Ethernet-Setup$' "$ETH"
grep -q '^autoconnect=true$' "$ETH"
grep -q '^autoconnect-retries=0$' "$ETH"
grep -q '^method=shared$' "$ETH"
grep -q '^address1=10.43.0.1/24' "$ETH"
grep -q '^never-default=true$' "$ETH"
sudo chroot "$ROOT" /bin/bash -c 'nmcli --offline connection modify type ethernet < /etc/NetworkManager/system-connections/2pny-ethernet-setup.nmconnection > /tmp/2pny-eth-roundtrip.nmconnection'
grep -q '^id=2PNY-Ethernet-Setup$' "$ROOT/tmp/2pny-eth-roundtrip.nmconnection"

echo '[5/9] recovery path is not the boot authority'
bash -n "$ROOT/usr/local/sbin/2pny-firstboot"
bash -n "$ROOT/usr/local/sbin/2pny-setup-watch"
bash -n "$ROOT/usr/local/sbin/2pny-ap-control"
grep -q 'MemoryMax=96M' "$ROOT/etc/systemd/system/2pny-setup-watch.service"
grep -q 'NetworkManager will retry automatically' "$ROOT/usr/local/sbin/2pny-setup-watch"
grep -q '2PNY-NETWORK.txt' "$ROOT/usr/local/sbin/2pny-setup-watch"
grep -q 'connection.autoconnect no' "$ROOT/usr/local/sbin/2pny-ap-control"
grep -q 'connection.autoconnect yes' "$ROOT/usr/local/sbin/2pny-ap-control"

echo '[6/9] captive portal and DNS contract'
grep -q 'address=/#/10.42.0.1' "$ROOT/etc/NetworkManager/dnsmasq-shared.d/2pny-captive.conf"
grep -aFq '/generate_204' "$ROOT/usr/local/bin/2pnyd"
grep -aFq '/hotspot-detect.html' "$ROOT/usr/local/bin/2pnyd"
grep -aFq '/api/ap' "$ROOT/usr/local/bin/2pnyd"

echo '[7/9] live ARM64 panel from final image'
sudo mkdir -p "$ROOT/proc" "$ROOT/dev" "$ROOT/sys" "$ROOT/run" "$ROOT/var/lib/2pny"
sudo mount -t proc proc "$ROOT/proc"
sudo mount --bind /dev "$ROOT/dev"
sudo mount --bind /sys "$ROOT/sys"
sudo chroot "$ROOT" /usr/local/bin/2pnyd >/tmp/2pnyd-018.log 2>&1 &
PID=$!
OK=0
for _ in {1..50}; do
  if curl -fsS http://127.0.0.1/healthz 2>/dev/null | grep -q '2PNY OK'; then OK=1; break; fi
  sleep .2
done
if [[ "$OK" != 1 ]]; then cat /tmp/2pnyd-018.log || true; exit 1; fi
curl -fsS http://127.0.0.1/wizard >/dev/null
CODE="$(curl -sS -o /dev/null -w '%{http_code}' http://127.0.0.1/generate_204)"
[[ "$CODE" == 302 ]]
sudo ss -ltn | grep -E '(0\.0\.0\.0|\*|\[::\]):80\b'
kill -0 "$PID"

echo '[8/9] RF features preserved'
test -x "$ROOT/usr/local/bin/MMDVM-Host"
grep -q '^DumpTAData=1$' "$ROOT/usr/local/sbin/2pny-rf-apply"
grep -q 'MemoryMax=64M' "$ROOT/etc/systemd/system/2pnyd.service"
grep -q 'MemoryMax=96M' "$ROOT/etc/systemd/system/2pny-mmdvmhost.service"

echo '[9/9] lean image and diagnostic escape hatch'
test ! -e "$ROOT/usr/bin/g++"
test ! -e "$ROOT/usr/bin/git"
test -w "$ROOT/boot/firmware"

echo '2PNY 0.1.8 final image: Trixie native NetworkManager contracts + panel runtime OK'
