/* Navigation language is local to this browser; technical diagnostics retain source text. */
(()=>{
const dictionary={
'Painel':['Dashboard','Panel'],'Painel principal':['Dashboard','Panel principal'],'Ao vivo':['Live','En vivo'],'Histórico':['History','Historial'],'Operadores':['Operators','Operadores'],'Rede':['Network','Red'],'Hardware':['Hardware','Hardware'],'Rádio & DMR':['Radio & DMR','Radio y DMR'],'Display':['Display','Pantalla'],'Diagnóstico':['Diagnostics','Diagnóstico'],'Configurações':['Settings','Configuración'],'Atualizar':['Refresh','Actualizar'],'Básico':['Basic','Básico'],'Expert':['Expert','Experto'],'Internet e rede local':['Internet and local network','Internet y red local'],'Atividade das últimas 24 horas':['Activity in the last 24 hours','Actividad de las últimas 24 horas'],'Operadores locais':['Local operators','Operadores locales'],'Atualizar visualização':['Refresh view','Actualizar vista'],'Indicativo':['Callsign','Indicativo'],'Nome':['Name','Nombre'],'Cidade':['City','Ciudad'],'País':['Country','País'],'Direção':['Direction','Dirección'],'Duração':['Duration','Duración'],'Horário':['Time','Hora'],'Protocolo':['Protocol','Protocolo'],'Atualizado':['Updated','Actualizado'],'TX · Seu rádio → Internet':['TX · Your radio → Internet','TX · Su radio → Internet'],'RX · Internet → seu rádio':['RX · Internet → Your radio','RX · Internet → Su radio'],'Você transmitindo pelo rádio':['You transmitting on the radio','Usted transmitiendo por radio'],'Você recebendo uma transmissão da rede':['You receiving a network transmission','Usted recibiendo una transmisión de la red'],'Conexão de rede':['Network connection','Conexión de red'],'Buscar redes':['Scan networks','Buscar redes'],'Continuar com cabo':['Continue with Ethernet','Continuar con cable'],'Continuar':['Continue','Continuar'],'Voltar':['Back','Volver'],'Configuração básica':['Basic configuration','Configuración básica'],'Servidor DMR':['DMR server','Servidor DMR'],'Pesquisar servidor':['Search server','Buscar servidor'],'Todos':['All','Todos'],'Senha do master':['Master password','Contraseña del master'],'Módulo XLX':['XLX module','Módulo XLX'],'Preparando hardware':['Preparing hardware','Preparando hardware'],'Salvar QRZ':['Save QRZ','Guardar QRZ'],'Remover credenciais':['Remove credentials','Eliminar credenciales'],'Habilitar SSH':['Enable SSH','Habilitar SSH'],'Desativar SSH':['Disable SSH','Desactivar SSH'],'Sistema / recepção':['System / reception','Sistema / recepción'],'Fotos QRZ':['QRZ photos','Fotos QRZ'],'Acessos rápidos':['Quick links','Accesos rápidos'],'Servidor digital':['Digital server','Servidor digital'],'Rádio':['Radio','Radio'],'Frequência':['Frequency','Frecuencia'],'Modo':['Mode','Modo'],'Internet offline':['Internet offline','Internet desconectada']
};
let language=localStorage.getItem('pu2pny-language')||'pt', originals=new WeakMap();
function translate(){let walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),node;while(node=walker.nextNode()){if(['SCRIPT','STYLE','OPTION'].includes(node.parentElement.tagName))continue;let text=node.textContent.trim(),base=originals.get(node);if(!base&&dictionary[text]){base=text;originals.set(node,base)}if(base){let wanted=language==='pt'?base:dictionary[base][language==='en'?0:1];if(text!==wanted)node.textContent=node.textContent.replace(text,wanted)}}document.documentElement.lang=language==='pt'?'pt-BR':language}
let selector=document.getElementById('language');if(selector){selector.value=language;selector.onchange=()=>{language=selector.value;localStorage.setItem('pu2pny-language',language);translate()}}
translate();window.translateNavigation=translate;
})();
